data:
  img_dir: /root/lanyun-tmp/seaLab/data/train_ssha_png
  lbl_dir: /root/lanyun-tmp/seaLab/data/train_mask_png
train:
  out_dir: results
  batch_size: 16
  epochs: 30
  lr: 0.0001
  weight_decay: 0.0001
  train_ratio: 0.8
  seed: 42
  device: cuda
  num_workers: 4
  pin_memory: true
  save_interval_steps: 1000
  save_interval_epochs: 5
  freeze_bn: true
model:
  num_classes: 3
  backbone: resnet50
  pretrained_backbone: false

evaluation:
  weights: results/best_model.pth
  result_dir: results
  device: cuda
  colors:
    - [0,0,255]
    - [255,255,255]
    - [0,255,0]
